### PR TITLE
Feat/92 - Add details of officials to calendar files

### LINKED ISSUE #92: [FEATURE REQUEST]: Add appointed umpires/officials to the match descriptions
### Explain your feature.

Add the details of appointed officials from Altius to the match descriptions

### Added value.

Initial feature to allow for personal calendar subscription

### Additional info

Self developed- Draft PR coming!

### PR DESCRIPTION
**Pull request by philipohagan**
Thank you for contributing to this application!

**Important**: make sure you create an issue first before submitting a pull request. Replace [ISSUE NUMBER] with the ID of the issue that is solved by this PR.

Closes #92

## Proposed Changes
_Explain the changes you've made with this PR_
- Add new object of 'Official'
- Add the ability (optionally) for the TMS fetcher to request Officals
- Scrape Officials from Altius
- Place the Officials for each match into the appropriate ICS files

## Checklist

- [x] I have read the [contribution document](https://github.com/Martijn-van-Kekem-Development/hockey-match-calendar/blob/main/CONTRIBUTING.md).
- [ ] I have added test cases to cover my changes (if applicable).
- [x] All new and existing test cases have passed.
- [x] My code adheres to the coding style of this project.

### CODE REVIEW

**Comment by philipohagan** [comment]
Still need to add tests before finalising

**Comment by philipohagan** [comment]
@martijnvankekem - know you are busy with watch rewrite but could you take a look at this when you get the chance?

**Comment by martijnvankekem** [comment]
Will take a look later this week.

**Review by martijnvankekem — CHANGES_REQUESTED** [review]
Although I like the idea of adding TMS appointments, I'm not a big fan of the current implementation.

Some notes:
- The current implementation iterates over all tab id's on the officials page. This is not necessary, since the data is not loaded dynamically. All data is already in the HTML as soon as the page finishes loading. Instead of iterating over all tabs, I'd like to see a simple querySelectorAll on all table rows.
- With the current implementation, all data is fetched twice, and therefore twice as many network requests are made (fetching is both done in TMSFetcher.ts at line 89, and in TMSCompetitionFetcher.ts at line 55).
- I don't like the hardcoded implementation of the several roles. When a different TMS system adds a custom role or gives it a different name, this fails. I'd like to see the column headers from TMS being used as the role name, and the different appointments being added dynamically based on the amount of available columns.
- Several added functions are missing docstrings.

I can imagine that what I have in my head is more clear than the way I'm able to put it on paper here. If you want, I can create a PR from scratch implementing this feature.

Let me know what you prefer!

**Comment by philipohagan** [comment]
Agree, let me do another go at it

**Pull request closed without merging**
